name: homo3d
channels:
  - conda-forge
  - defaults
dependencies:
  - mkl=2021.4.0
  - xz=5.2.10
  - bzip2=1.0.8
  - icu=72.1
  - ilmbase=2.5.5
  - libexpat=2.5.0
  - blosc=1.21.3
  - zstd=1.5.5
  - wheel=0.38.4
  - libffi=3.4.2
  - tbb=2018.0.5
  - lz4-c=1.9.4
  - ca-certificates=2022.12.7
  - tbb-devel=2018.0.5
  - mkl_random=1.2.2
  - eigen=3.4.0
  - blas=1.0
  - python=3.11.3
  - _libgcc_mutex=0.1
  - glm=0.9.9.4
  - gflags=2.2.2
  - python_abi=3.11
  - setuptools=66.0.0
  - openssl=3.1.0
  - mkl_fft=1.3.1
  - numpy=1.24.3
  - boost=1.82.0
  - libsqlite=3.40.0
  - tk=8.6.12
  - intel-openmp=2021.4.0
  - snappy=1.1.9
  - boost-cpp=1.82.0
  - numpy-base=1.24.3
  - mkl-service=2.4.0
  - pip=23.0.1
  - tzdata=2023c
  - six=1.16.0
  - libzlib=1.2.13
  - zlib=1.2.13
